"""
Even Fibonacci Numbers
Problem 2

Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2 , the first 10 terms will be:
1, 2, 3, 5, 8, 13, 21, 34, 55, 89

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

"""

def evenFibonacciNumbers()->list:
    i=0
    liste = [1,2]
    while(i<8) :
        a = liste[i]
        b = liste[i+1]
        sum = a+b
        i+=1
        liste.append(sum)
    return liste

print(f"{evenFibonacciNumbers()}")