"""
Even Fibonacci Numbers
Problem 2

Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2 , the first 10 terms will be:
1, 2, 3, 5, 8, 13, 21, 34, 55, 89

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

"""
def evenFibonacciNumbers()->list:
    i=0
    liste = [1,2]
    while(i<100-2) :
        a = liste[-1]
        b = liste[-2]
        sum = a+b
        liste.append(sum)
        i+=1
    print(f"Voici la liste des nombres de fibinacci:\n{liste}")
    return [x for x in liste if x%2==0]

print(f"Voici la liste des nombre de fibinacci pairs:\n{evenFibonacciNumbers()}")
print(f"Voici la somme des nombre de fibinacci pairs:\n{sum(evenFibonacciNumbers())}")